
version: '3'

services:
  frontend:
    build:
      context: ./websiteAngular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./websiteAngular:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./website-api
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./website-api:/app
      - /app/node_modules
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi_password
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: